### ISSUE TITLE
MySQL configuration is using the wrong 'host' value

### ISSUE THREAD

**Issue by tykeal** [bramwelt/puppet-patchwork#8]
The host variable that is being passed to mysql::db for both the exported, as well as non-exported resource is not correct.

You're passing the database location in and not the information of the client machine that should be connecting. This causes the resource to be created (or tried to be created) on the MySQL collection side to create incorrect user records.

I would recommend that it should be set to $::ipaddress or $::fqdn or some other value that defaults to one of those.

**Comment by bramwelt** [comment]
Resolve in #9
